/**
 * FreeFoodMap — 全球免费食品发放点数据
 * 数据来源:各组织官网、Feeding America 网络、Trussell Trust、European Food Banks Federation 等
 * 标注仅作示例与教育用途,具体服务时间请以各机构最新公布为准。
 */
window.FOOD_POINTS = [
  // ===== 北美 — 美国 =====
  {
    id: "us-feeding-america-hq",
    name: "Feeding America (总部)",
    org: "Feeding America",
    city: "Chicago, IL",
    country: "USA",
    lat: 41.8819, lng: -87.6278,
    type: "foodbank",
    schedule: "全美 200+ 食品银行网络",
    phone: "1-800-771-2303",
    website: "https://www.feedingamerica.org/",
    desc: "美国最大饥饿救济网络,旗下 200+ 家食品银行,每年向 4000+ 万人分发约 39 亿磅食物。",
    video: ""
  },
  {
    id: "us-fbnyc",
    name: "Food Bank For New York City",
    org: "Food Bank For NYC",
    city: "New York, NY",
    country: "USA",
    lat: 40.7549, lng: -73.9911,
    type: "foodbank",
    schedule: "周一–周五 9:00–17:00;近 800 个合作分发点",
    phone: "(212) 566-7855",
    website: "https://www.foodbanknyc.org/",
    desc: "40+ 年服务纽约客,迄今已分发 16 亿磅营养食物,惠及 130 万纽约人。",
    video: ""
  },
  {
    id: "us-freestore",
    name: "Freestore Foodbank",
    org: "Freestore Foodbank",
    city: "Cincinnati, OH",
    country: "USA",
    lat: 39.1031, lng: -84.5120,
    type: "foodbank",
    schedule: "全年分发,详情见官网",
    phone: "(513) 482-4500",
    website: "https://www.feedingamerica.org/find-your-local-foodbank/freestore-foodbank",
    desc: "大辛辛那提地区最大食品银行,2024 年通过其网络分发了数千万磅食物。",
    video: ""
  },
  {
    id: "us-faith-temple",
    name: "Faith Temple Food Giveaway",
    org: "Faith Temple Food",
    city: "Sioux Falls, SD",
    country: "USA",
    lat: 43.5446, lng: -96.7311,
    type: "weekly",
    schedule: "每周五免费发放",
    phone: "(605) 332-2222",
    website: "http://www.faithtemplefood.com/",
    desc: "每周五向社区 4000+ 人免费发放食物、婴儿用品、卫生用品。",
    video: ""
  },
  {
    id: "us-oldtown",
    name: "Old Town Mission",
    org: "Old Town Mission",
    city: "Loveland, CO",
    country: "USA",
    lat: 40.3978, lng: -105.0749,
    type: "pantry",
    schedule: "周一–周五 9:00–16:00",
    phone: "(970) 593-0101",
    website: "https://www.oldtownmission.org/",
    desc: "2025 年分发 47,900 份食物盒、提供 26,656 份免费餐;为无家可归者提供淋浴与理发。",
    video: ""
  },
  {
    id: "us-broadway",
    name: "Broadway Community",
    org: "Broadway Community Inc.",
    city: "New York, NY",
    country: "USA",
    lat: 40.8081, lng: -73.9637,
    type: "soup_kitchen",
    schedule: "周一/二/三/五 提供早午餐",
    phone: "(212) 864-6100 ext.120",
    website: "https://www.broadwaycommunity.org/",
    desc: "40+ 年服务纽约客的\"四星\"社区厨房,2025 年提供 37,294 份热餐、4,096 份食物包。",
    video: ""
  },
  {
    id: "us-feed-our-vets",
    name: "Feed Our Vets",
    org: "Feed Our Vets",
    city: "Utica, NY",
    country: "USA",
    lat: 43.1009, lng: -75.2327,
    type: "pantry",
    schedule: "工作日开放",
    phone: "(315) 733-1600",
    website: "http://feedourvets.org/",
    desc: "2009 年起服务退伍军人及家属,已分发 600 万磅食物、43,000 美元礼品卡。",
    video: ""
  },
  {
    id: "us-rcs",
    name: "Religious Community Services",
    org: "RCS New Bern",
    city: "New Bern, NC",
    country: "USA",
    lat: 35.1085, lng: -77.0441,
    type: "pantry",
    schedule: "周一–周五 9:00–16:00",
    phone: "(252) 633-2767",
    website: "https://www.rcsnewbern.org/",
    desc: "1982 年起服务北卡东部社区,2025 年分发 47,449 份餐食。",
    video: ""
  },
  {
    id: "us-minnie-pantry",
    name: "Minnie's Food Pantry",
    org: "Minnie's Food Pantry Foundation",
    city: "Plano, TX",
    country: "USA",
    lat: 33.0198, lng: -96.6989,
    type: "drive_thru",
    schedule: "定期 drive-through 分发",
    phone: "(972) 422-4100",
    website: "https://minniesfoodpantry.org/",
    desc: "得州知名 drive-through 食品发放,每次可服务 750+ 家庭。",
    video: ""
  },
  {
    id: "us-la-sauce-pancake-tang",
    name: "小唐酱香饼(贫民区免费发放点)",
    org: "小唐 × 粉丝自发",
    city: "Los Angeles, CA",
    country: "USA",
    lat: 34.0407, lng: -118.2468,
    type: "street",
    schedule: "不定期出摊,详见抖音 @xiaotang688",
    phone: "(抖音) xiaotang688",
    website: "https://www.douyin.com/user/MS4wLjABAAAAZxRtzIGZqJrcf-8rddZHaI7RM45SRwZrgSSDhstUBEc",
    desc: "2022 年独闯洛杉矶的河南小伙,从 60 美元/张的酱香饼到贫民区免费发饼,2026 年宣布竞选洛杉矶市长。视频全网千万级播放。",
    video: "BV1i7gaz4EAm"
  },
  // ===== 北美 — 加拿大 =====
  {
    id: "ca-fbcanada",
    name: "Food Banks Canada",
    org: "Food Banks Canada",
    city: "Toronto, ON",
    country: "Canada",
    lat: 43.6532, lng: -79.3832,
    type: "foodbank",
    schedule: "全国 4,500+ 食品发放点",
    phone: "(416) 203-9241",
    website: "https://www.foodbankscanada.ca/",
    desc: "覆盖加拿大全境的食品银行网络,服务移民、儿童、残障群体。",
    video: ""
  },
  {
    id: "ca-daily-bread",
    name: "Daily Bread Food Bank",
    org: "Daily Bread",
    city: "Toronto, ON",
    country: "Canada",
    lat: 43.6629, lng: -79.3762,
    type: "foodbank",
    schedule: "周一–周五",
    phone: "(416) 203-0050",
    website: "https://www.dailybread.ca/",
    desc: "多伦多最大食品银行,2024 年服务超 30 万人次。",
    video: ""
  },
  // ===== 欧洲 — 英国 =====
  {
    id: "uk-trussell",
    name: "Trussell Trust (网络)",
    org: "Trussell Trust",
    city: "Salisbury",
    country: "UK",
    lat: 51.0688, lng: -1.7945,
    type: "foodbank",
    schedule: "全英 1,400+ 转介中心",
    phone: "0808 208 2138",
    website: "https://www.trussell.org.uk/",
    desc: "英国最大紧急食品包网络,2023–24 年发放约 310 万份三日紧急食品包。",
    video: ""
  },
  {
    id: "uk-blackcountry",
    name: "Black Country Foodbank",
    org: "Black Country Foodbank",
    city: "Wolverhampton",
    country: "UK",
    lat: 52.5862, lng: -2.1280,
    type: "foodbank",
    schedule: "Dudley / Sandwell / Walsall 分发点",
    phone: "01902 712 011",
    website: "https://www.blackcountryfoodbank.org.uk/",
    desc: "为陷入危机的人提供 3 天紧急食物补给,2025 年服务覆盖整个黑乡地区。",
    video: ""
  },
  // ===== 欧洲 — 比利时 =====
  {
    id: "be-feb",
    name: "Fédération Belge des Banques Alimentaires",
    org: "Belgian Federation of Food Banks",
    city: "Brussels",
    country: "Belgium",
    lat: 50.8503, lng: 4.3517,
    type: "foodbank",
    schedule: "全国 665+ 协会分发点",
    phone: "+32 2 521 28 00",
    website: "https://www.foodbanks.be/",
    desc: "比利时食物银行联合会,1985 年成立,每年向 10 万穷人分发约 7,700 吨食物。",
    video: ""
  },
  // ===== 欧洲 — 法国 =====
  {
    id: "fr-ffba",
    name: "Fédération Française des Banques Alimentaires",
    org: "FFBA",
    city: "Paris",
    country: "France",
    lat: 48.8566, lng: 2.3522,
    type: "foodbank",
    schedule: "全国 79 家食品银行 + 5,400 协会",
    phone: "+33 1 49 82 38 00",
    website: "https://www.banquealimentaire.org/",
    desc: "法国最大食品银行网络,1984 年成立,服务约 240 万人。",
    video: ""
  },
  // ===== 欧洲 — 德国 =====
  {
    id: "de-tafel",
    name: "Tafel Deutschland (总部)",
    org: "Tafel Deutschland e.V.",
    city: "Berlin",
    country: "Germany",
    lat: 52.5200, lng: 13.4050,
    type: "foodbank",
    schedule: "全国 960+ Tafel 分发点",
    phone: "+49 30 200 59 26 0",
    website: "https://www.tafel.de/",
    desc: "德国最大食物救助网络,每周向 96 万人提供食物;以志愿者为主。",
    video: ""
  },
  // ===== 欧洲 — 西班牙 =====
  {
    id: "es-fesbal",
    name: "FESBAL",
    org: "Federación Española de Bancos de Alimentos",
    city: "Madrid",
    country: "Spain",
    lat: 40.4168, lng: -3.7038,
    type: "foodbank",
    schedule: "全国 54 家食品银行",
    phone: "+34 91 522 49 00",
    website: "https://www.fesbal.org/",
    desc: "西班牙食物银行联合会,服务约 100 万人。",
    video: ""
  },
  // ===== 欧洲 — 意大利 =====
  {
    id: "it-fondazione",
    name: "Fondazione Banco Alimentare Onlus",
    org: "Banco Alimentare",
    city: "Milan",
    country: "Italy",
    lat: 45.4642, lng: 9.1900,
    type: "foodbank",
    schedule: "全国 21 家食品银行",
    phone: "+39 02 4070 5320",
    website: "https://www.bancoalimentare.it/",
    desc: "意大利最大食物银行网络,1989 年成立,服务 7,500+ 慈善组织。",
    video: ""
  },
  // ===== 欧洲 — 波兰 =====
  {
    id: "pl-fpbz",
    name: "Polski Komitet Pomocy Społecznej",
    org: "Polish Federation of Food Banks",
    city: "Warsaw",
    country: "Poland",
    lat: 52.2297, lng: 21.0122,
    type: "foodbank",
    schedule: "全国 200+ 合作组织",
    phone: "+48 22 626 41 00",
    website: "https://www.fpbbz.pl/",
    desc: "波兰最大食物银行网络,与欧盟食物援助基金对接。",
    video: ""
  },
  // ===== 欧洲 — 葡萄牙 =====
  {
    id: "pt-fban",
    name: "Federação Portuguesa dos Bancos Alimentares",
    org: "FPBA",
    city: "Lisbon",
    country: "Portugal",
    lat: 38.7223, lng: -9.1393,
    type: "foodbank",
    schedule: "全国 18 家食品银行",
    phone: "+351 21 886 60 00",
    website: "https://www.bancoalimentar.pt/",
    desc: "葡萄牙食物银行联合会,服务全国 2,000+ 慈善机构。",
    video: ""
  },
  // ===== 欧洲 — 瑞士、奥地利、希腊、荷兰 =====
  {
    id: "ch-table",
    name: "Schweizer Tafel",
    org: "Schweizer Tafel",
    city: "Zürich",
    country: "Switzerland",
    lat: 47.3769, lng: 8.5417,
    type: "foodbank",
    schedule: "全国 19 个分发点",
    phone: "+41 44 586 80 80",
    website: "https://www.schweizertafel.ch/",
    desc: "瑞士最大食物银行,2001 年成立,每年挽救约 6,000 吨本要被浪费的食品。",
    video: ""
  },
  {
    id: "nl-voedselbank",
    name: "Voedselbanken Nederland",
    org: "Dutch Food Bank",
    city: "Utrecht",
    country: "Netherlands",
    lat: 52.0907, lng: 5.1214,
    type: "foodbank",
    schedule: "全国 175 家分发点",
    phone: "+31 30 236 38 00",
    website: "https://www.voedselbankennederland.nl/",
    desc: "荷兰最大食物银行网络,每周服务约 3.5 万人。",
    video: ""
  },
  // ===== 中国 =====
  {
    id: "cn-luzhou",
    name: "绿洲盛食社 (上海总部)",
    org: "上海绿洲公益发展中心",
    city: "上海",
    country: "China",
    lat: 31.2304, lng: 121.4737,
    type: "foodbank",
    schedule: "全国 15+ 省市、344 个授权分发点",
    phone: "+86 21 6321 1000",
    website: "https://www.oasisbank.org.cn/",
    desc: "中国本土首家食物银行,2015 年成立,累计挽救 1000+ 吨余量食物,惠及 110 万人次。",
    video: ""
  },
  {
    id: "cn-kfc-bj",
    name: "肯德基食物银行·北京",
    org: "百胜中国 KFC",
    city: "北京",
    country: "China",
    lat: 39.9042, lng: 116.4074,
    type: "smart_cabinet",
    schedule: "每日上架,免费领取",
    phone: "400-883-8881",
    website: "https://www.yumchina.com/",
    desc: "将餐厅余量食物放入社区智能柜,北京、上海、深圳等多城已上线。",
    video: ""
  },
  {
    id: "cn-kfc-sh",
    name: "肯德基食物银行·上海",
    org: "百胜中国 KFC",
    city: "上海",
    country: "China",
    lat: 31.2304, lng: 121.4737,
    type: "smart_cabinet",
    schedule: "每日上架,免费领取",
    phone: "400-883-8881",
    website: "https://www.yumchina.com/",
    desc: "全国首创社区骑手驿站常态化公益联动模式,将余量食物延伸至社区一线。",
    video: ""
  },
  {
    id: "cn-kfc-sz",
    name: "肯德基食物银行·深圳(智能食物柜)",
    org: "百胜中国 KFC",
    city: "深圳",
    country: "China",
    lat: 22.5431, lng: 114.0579,
    type: "smart_cabinet",
    schedule: "线上预约,线下柜机领取",
    phone: "400-883-8881",
    website: "https://www.yumchina.com/",
    desc: "深圳街头的智能食物柜,只存取食物;2024 年起推广至更多城市。",
    video: ""
  },
  {
    id: "cn-hk-stjames",
    name: "圣雅各福群会食物银行",
    org: "St. James' Settlement",
    city: "Hong Kong",
    country: "China (HK)",
    lat: 22.3310, lng: 114.1580,
    type: "foodbank",
    schedule: "石硖尾等多处分发点",
    phone: "+852 2831 3259",
    website: "https://www.sjs.org.hk/",
    desc: "香港最大食物援助网络之一,2008 年港府正式推行食物银行计划。",
    video: ""
  },
  // ===== 亚太 =====
  {
    id: "sg-fbsg",
    name: "Food Bank Singapore",
    org: "The Food Bank Singapore",
    city: "Singapore",
    country: "Singapore",
    lat: 1.3521, lng: 103.8198,
    type: "foodbank",
    schedule: "全年分发",
    phone: "+65 6817 9840",
    website: "https://www.foodbank.sg/",
    desc: "新加坡最大食物银行,2012 年成立,分发网络覆盖 400+ 慈善机构。",
    video: ""
  },
  {
    id: "au-foodbank-au",
    name: "Foodbank Australia",
    org: "Foodbank Australia",
    city: "Sydney",
    country: "Australia",
    lat: -33.8688, lng: 151.2093,
    type: "foodbank",
    schedule: "全国网络",
    phone: "+61 2 8868 8100",
    website: "https://www.foodbank.org.au/",
    desc: "澳大利亚最大饥饿救济组织,每年分发 8,000 万公斤食物。",
    video: ""
  },
  {
    id: "nz-kfb",
    name: "KiwiHarvest",
    org: "KiwiHarvest",
    city: "Auckland",
    country: "New Zealand",
    lat: -36.8485, lng: 174.7633,
    type: "foodbank",
    schedule: "全国分发",
    phone: "+64 9 309 6500",
    website: "https://www.kiwiharvest.org.nz/",
    desc: "新西兰最大食物救助网络,2024 年分发 400 万公斤食物。",
    video: ""
  },
  {
    id: "jp-secondharvest",
    name: "Second Harvest Japan (認定NPO法人)",
    org: "2Harvest",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6762, lng: 139.6503,
    type: "foodbank",
    schedule: "全国网络",
    phone: "+81 3 3526 1083",
    website: "https://www.2hj.org/",
    desc: "日本最大食物银行,2002 年成立,服务全国 5,000+ 受助者。",
    video: ""
  },
  {
    id: "kr-foodbank-korea",
    name: "대한민국식품은행 (Korea Food Bank)",
    org: "KFBA",
    city: "Seoul",
    country: "South Korea",
    lat: 37.5665, lng: 126.9780,
    type: "foodbank",
    schedule: "全国 90+ 分发点",
    phone: "+82 2 745 2700",
    website: "https://www.kfba.or.kr/",
    desc: "韩国最大食物银行网络,1998 年成立。",
    video: ""
  },
  {
    id: "in-robin-hood",
    name: "Robin Hood Army",
    org: "Robin Hood Army",
    city: "Mumbai",
    country: "India",
    lat: 19.0760, lng: 72.8777,
    type: "street",
    schedule: "志愿者自发,周末分发",
    phone: "(Instagram) robinhoodarmy",
    website: "https://robinhoodarmy.com/",
    desc: "印度及全球 100+ 城市志愿者网络,直接在街头/餐厅为饥饿者分发食物。",
    video: ""
  },
  // ===== 拉丁美洲 =====
  {
    id: "mx-bamx",
    name: "Bancos de Alimentos de México",
    org: "BAMX",
    city: "Mexico City",
    country: "Mexico",
    lat: 19.4326, lng: -99.1332,
    type: "foodbank",
    schedule: "全国 55 家食品银行",
    phone: "+52 55 5559 1616",
    website: "https://www.bamx.org.mx/",
    desc: "墨西哥最大食物银行网络,1995 年成立,服务 100 万+ 弱势群体。",
    video: ""
  },
  {
    id: "br-mesa",
    name: "Mesa Brasil SESC",
    org: "SESC",
    city: "São Paulo",
    country: "Brazil",
    lat: -23.5505, lng: -46.6333,
    type: "foodbank",
    schedule: "全国 100+ 分发点",
    phone: "+55 11 3236 3000",
    website: "https://www.mesabrasil.org.br/",
    desc: "巴西最大食物银行,1994 年成立,每月向 70 万人分发 150 万公斤食物。",
    video: ""
  },
  {
    id: "ar-aba",
    name: "Asociación de Bancos de Alimentos de Argentina",
    org: "ABA",
    city: "Buenos Aires",
    country: "Argentina",
    lat: -34.6037, lng: -58.3816,
    type: "foodbank",
    schedule: "全国网络",
    phone: "+54 11 4322 8800",
    website: "https://www.redbda.org/",
    desc: "阿根廷食物银行联合会,2003 年成立。",
    video: ""
  },
  {
    id: "cl-bac",
    name: "Banco Central de Alimentos de Chile",
    org: "BCA Chile",
    city: "Santiago",
    country: "Chile",
    lat: -33.4489, lng: -70.6693,
    type: "foodbank",
    schedule: "首都 + 全国分发",
    phone: "+56 2 2671 1100",
    website: "https://www.bancodealimentos.cl/",
    desc: "智利最大食物银行,服务 80+ 慈善机构。",
    video: ""
  },
  {
    id: "co-abacoa",
    name: "Asociación de Bancos de Alimentos de Colombia",
    org: "ABACO",
    city: "Bogotá",
    country: "Colombia",
    lat: 4.7110, lng: -74.0721,
    type: "foodbank",
    schedule: "全国 23 家食品银行",
    phone: "+57 1 744 7900",
    website: "https://www.abaco.org.co/",
    desc: "哥伦比亚食物银行网络,2001 年成立。",
    video: ""
  },
  // ===== 非洲 =====
  {
    id: "za-fabsa",
    name: "FoodBank South Africa",
    org: "FoodBank SA",
    city: "Johannesburg",
    country: "South Africa",
    lat: -26.2041, lng: 28.0473,
    type: "foodbank",
    schedule: "全国 800+ 食物分发点",
    phone: "+27 11 453 8511",
    website: "https://www.foodbank.org.za/",
    desc: "南非最大食物银行,2009 年成立,每天分发 5,000+ 份食物。",
    video: ""
  },
  {
    id: "ke-foodforkenya",
    name: "Food for Education",
    org: "Food4Education",
    city: "Nairobi",
    country: "Kenya",
    lat: -1.2921, lng: 36.8219,
    type: "school_meal",
    schedule: "学校供餐计划",
    phone: "+254 20 765 7080",
    website: "https://www.food4education.org/",
    desc: "肯尼亚校园餐计划,通过 Tap & Eat 数字系统为小学生提供热餐。",
    video: ""
  },
  {
    id: "ng-fbcf",
    name: "FoodBank-CF",
    org: "FoodBank of Central Florida",
    city: "Orlando, FL (Lagos partner)",
    country: "Nigeria",
    lat: 6.5244, lng: 3.3792,
    type: "foodbank",
    schedule: "拉各斯及周边",
    phone: "(Lagos network)",
    website: "https://www.foodbankcfl.org/",
    desc: "尼日利亚食物银行网络,服务于全球饥饿人口最多的地区之一。",
    video: ""
  },
  // ===== 大洋洲及其他 =====
  {
    id: "us-fb-hi",
    name: "Hawaii Foodbank",
    org: "Hawaii Foodbank",
    city: "Honolulu, HI",
    country: "USA",
    lat: 21.3069, lng: -157.8583,
    type: "foodbank",
    schedule: "周一–周六",
    phone: "(808) 836-3600",
    website: "https://www.hawaiifoodbank.org/",
    desc: "夏威夷最大食物银行,与 Feeding America 联网。",
    video: ""
  },
  // ===== 中东 & 土耳其 =====
  {
    id: "tr-tkgm",
    name: "Türk Kızılay (Turkish Red Crescent)",
    org: "Turkish Red Crescent",
    city: "Ankara",
    country: "Türkiye",
    lat: 39.9334, lng: 32.8597,
    type: "foodbank",
    schedule: "全国 + 应急救援",
    phone: "+90 312 430 2000",
    website: "https://www.kizilay.org.tr/",
    desc: "土耳其红新月会,在自然灾害、疫情时期为数百万人提供食物援助。",
    video: ""
  },
  {
    id: "ae-fbr",
    name: "Food Bank - UAE (IHC)",
    org: "International Humanitarian City",
    city: "Dubai",
    country: "UAE",
    lat: 25.2048, lng: 55.2708,
    type: "foodbank",
    schedule: "全国食物援助",
    phone: "+971 4 883 5555",
    website: "https://www.ihc.ae/",
    desc: "阿联酋最大食物援助枢纽,与联合国世界粮食计划署对接。",
    video: ""
  },
  {
    id: "il-lakol",
    name: "Lakol Tov / Le'kchem",
    org: "Latet",
    city: "Tel Aviv",
    country: "Israel",
    lat: 32.0853, lng: 34.7818,
    type: "foodbank",
    schedule: "全国分发",
    phone: "+972 3 528 1111",
    website: "https://www.latet.org.il/",
    desc: "以色列最大食物救助 NGO,2024 年分发 900 万份餐食。",
    video: ""
  }
];

window.TYPE_LABELS = {
  zh: {
    foodbank: "Food Bank / 食物银行",
    pantry: "Food Pantry / 食物柜",
    soup_kitchen: "Soup Kitchen / 流动餐车",
    street: "Street Distribution / 街头免费发放",
    weekly: "Weekly Giveaway / 每周发放",
    drive_thru: "Drive-Through / 免下车领取",
    school_meal: "School Meal / 校园供餐",
    smart_cabinet: "Smart Cabinet / 智能食物柜"
  },
  en: {
    foodbank: "Food Bank",
    pantry: "Food Pantry",
    soup_kitchen: "Soup Kitchen",
    street: "Street Distribution",
    weekly: "Weekly Giveaway",
    drive_thru: "Drive-Through",
    school_meal: "School Meal",
    smart_cabinet: "Smart Cabinet"
  }
};

window.TYPE_COLORS = {
  foodbank: "#f97316",
  pantry: "#fbbf24",
  soup_kitchen: "#10b981",
  street: "#ef4444",
  weekly: "#a78bfa",
  drive_thru: "#06b6d4",
  school_meal: "#84cc16",
  smart_cabinet: "#ec4899"
};
